#page title
page_title                                : Tap Rush Challenge                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6749596866                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Fast-paced number tapping game with 5 unique modes and global leaderboards.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Raquel Pajuelo
your_link                                 :
your_city                                 : Madrid
email_address                             : dev.genius.lemon@gmail.com
linkedin_username                         :
linkedin_company                          :
facebook_username                         :                                           
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Classic Mode
    description                           : Count from 1 to the highest number without distractions.
    fontawesome_icon_name                 : list-ol

  - title                                 : Reverse Mode
    description                           : Start from the highest number and race down to 1.
    fontawesome_icon_name                 : sync

  - title                                 : Time Attack
    description                           : Beat the clock with an integrated timer.
    fontawesome_icon_name                 : stopwatch

  - title                                 : Random Mode
    description                           : Tap before the numbers move to a new position.
    fontawesome_icon_name                 : random

  - title                                 : Memory Mode
    description                           : Memorize positions and hit numbers in the correct order.
    fontawesome_icon_name                 : puzzle-piece

  - title                                 : Global Leaderboards
    description                           : Compete worldwide with Game Center rankings for every mode and difficulty.
    fontawesome_icon_name                 : trophy

  - title                                 : Player Stats
    description                           : Track your games played, best times, and personal records.
    fontawesome_icon_name                 : chart-line

  - title                                 : Smooth Animations
    description                           : Enjoy fluid transitions and haptic feedback for every tap.
    fontawesome_icon_name                 : magic

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#0a0f1c"
topbar_transparency                       : 0.4
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#0a0f1c"

link_color                                : "#2b6cb0"

app_title_color                           : "#ffffff"
app_price_color                           : "#d4af37"
app_description_color                     : "#e2e8f0"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#cbd5e0"

feature_icons_foreground_color            : "#d4af37"
feature_icons_background_color            : "#1a202c"

social_icons_foreground_color             : "#e2e8f0"
social_icons_background_color             : "#1a202c"

footer_text_color                         : "#a0aec0"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
